content:
  - name: release_notes
    label: Release Notes
    path: _release_notes
    type: collection
    filename: "{primary}.md"
    subfolders: false
    fields:
      - name: slug
        label: Version
        type: string
        required: true
      - name: version_secondary
        label: Secondary Version
        type: string
        required: false
        description: For specific versions that has both a 0.xx.x string and a YYYY.MM.x string.
      - name: date
        label: Date
        type: date
        required: true
        options:
          format: MMMM DD, YYYY
    view:
      primary: slug
      fields: [ slug, date ]
      default:
        search: ''
        sort: date
        order: desc
  - name: posts
    label: Blog Posts
    path: _posts
    type: collection
    subfolders: false
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: date
        label: Date
        type: date
        required: true